# Generated by Django 6.1.1 on 2026-09-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=200)),
                ("auteur", models.CharField(max_length=150)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("annee_publication", models.PositiveIntegerField()),
                ("exemplaires_total", models.PositiveIntegerField(default=1)),
                ("exemplaires_disponible", models.PositiveIntegerField(default=1)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livres",
                        to="categories.categorie",
                    ),
                ),
            ],
            options={
                "ordering": ["titre"],
                "indexes": [
                    models.Index(fields=["titre"], name="livres_livr_titre_7cb81f_idx"),
                    models.Index(fields=["auteur"], name="livres_livr_auteur_5647a2_idx"),
                ],
            },
        ),
    ]
