# Generated by Django 6.1.1 on 2026-09-28 11:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numero de telephone Invalide",
                                regex="=^\\+?[0-9]\\s\\-]{8,20}$",
                            )
                        ],
                    ),
                ),
                ("date_inscription", models.DateField(default=django.utils.timezone.now)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nom", "prenom"],
                "indexes": [
                    models.Index(fields=["nom", "prenom"], name="membres_mem_nom_849d64_idx")
                ],
            },
        ),
    ]
