# Generated by Django 6.1.1 on 2026-09-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
