# Generated by Django 6.1.1 on 2026-09-28 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membres", "0002_alter_membre_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="date_inscription",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
